language: go
go:
  - 1.15
  - tip
notifications:
  email:
    recipients: dds@bosabosa.org
    on_success: change
    on_failure: always

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
